# **_Edel Corcoran ID #:G00010824_**
# **_GMIT: Higher Diploma in Data Analytics_**
# **_Module 52465: Programming for Data Analytics_**
# **_Assignment: NumPy.Random Package_**

# Introduction & Project Layout

The primary focus of this project is to  research the numpy.random package, to explain it's overall purpose and analyse in detail at least five of the distributions within the package and also to investigate the use of both the "Simple Random Data" and "Permutation" functions. Finally the project will outline how numpy.random uses seeds in generating psuedorandom numbers. 

The project layout
1. What is the numpy.random package
2. What is the overall purpose of the package
3. Explanation of the "Simple Random Data" function
4. Explanation of the "Permutation" function
5. Use/Purpose of 5 dictributions functions of numpy.random
6. Use of seeds in generating pseudorandom numbers
7. Summary
8. References/Biblography


# _1. What is numpy.random?_

"NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more." [1]

Essentially numpy is good and quick at dealing with numbers in big lists or matrices in python. If you need to deal with numbers you could write some code in python however numpy is simply a far more efficient way for you to deal with number lists or matrices in python. This specialist package deals with multi-dimensional arrays (ie. lists within lists) and it likes them to have a rectangular so two dimensionals lists each row/column having the same number of elements.  

Numpy.random is a sub-package of the NumPy package in python. 

Further information on the functions, permutations, distributions and random generator available within the numpy.random package is available on the website below:

https://docs.scipy.org/doc/numpy-1.15.0/reference/routines.random.html


# _2. Purpose of the package_

"NumPy is a data manipulation module for Python. Specifically, the tools from NumPy operate on arrays of numbers … i.e., numeric data. Because NumPy functions operate on numbers, they are especially useful for data science, statistics, and machine learning".[2]

It's a specialise package which help users to efficiently deal with lists of numbers or matrices in python. It's important for the simple reason that matrice operations are commonly utilised in computers and computer screens. Some tasks which require matrice operations are:

- resizing photographs
- compressing images or songs down to a particular size
- doing anything scientific on a computer



# 3. Permutations



Shuffle:

The NumPy arange function will produce an array with evenly spaced numerical values within a given range. In the example below an array with five values is produced from 0  to 4.


In [9]:
import numpy as np
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

The shuffle function will take the array produced above and shuffle it. The same five values are produced but now they are shuffled and appear in a different order as seen below:

In [10]:
arr = np.arange(5)
np.random.shuffle(array)
arr


array([0, 1, 2, 3, 4])

Permutation:

In [24]:
import numpy as np
np.random.permutation(5)

array([4, 1, 3, 0, 2])

# 6. Use of Seeds in generating Pseudorandom Numbers

“The NumPy random choice function operates on the principle of pseudorandom number generation. When we use a pseudorandom number generator, the numbers in the output approximate random numbers, but are not exactly ‘random’. In fact, when we use pseudorandom numbers, the output is actually deterministic; the output is actually determined by an initializing value called a ‘seed’. Let me say that again: when we set a seed for a pseudorandom number generator, the output is completely determined by the seed. What that means is that if we use the same seed, a pseudorandom number generator will produce the same output.”[3]


# _8. References/Biblography_

[1] https://docs.scipy.org/doc/numpy-1.15.0/user/whatisnumpy.html accessed 1/Nov/2019

[2] https://www.sharpsightlabs.com/blog/numpy-random-choice/ accessed 4/Nov/2019

[3] https://www.sharpsightlabs.com/blog/numpy-random-choice/ accessed 6/Nov/2019

https://docs.scipy.org/doc/numpy-1.15.0/reference/routines.random.html
